using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace FlightORM.Core
{
	[DataContract]
	public class QueryDefinition : StoreableBase<QueryDefinition>
	{
		public enum SourceType {
			[EnumMember]
			Autogenerated,
			[EnumMember]
			User
		}

		[DataMember]
		public Guid Id { get; set; }
		[DataMember]
		public string Name { get; set; }
		[DataMember]
		public bool IsModified { get; set; }
		[DataMember]
		public SourceType Source { get; set; }

		[DataMember]
		public TypeDefinition InputType { get; private set; }

		[DataMember]
		public TypeDefinition OutputType { get; private set; }

	}
}
